inherit_from: .rubocop_todo.yml

# Allow compact style in the tests.
Style/ClassAndModuleChildren:
  Exclude:
    - 'test/**/*'

# Don't require doc comments in general.
Style/Documentation:
  Enabled: false

# Use brackets for defining word arrays.
Style/WordArray:
  EnforcedStyle: brackets

# Allow complex methods
Metrics/AbcSize:
  Max: 35

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

# Allow long methods
Metrics/MethodLength:
  Max: 50

# Allow short param names.
Naming/UncommunicativeMethodParamName:
  Enabled: false

# Allow chaining blocks for solution efficiency.
Style/MultilineBlockChain:
  Enabled: false
