language: ruby

sudo: false

cache: bundler

before_install:
  - gem install bundler -v 1.16.1
  - ./test/install-libz3.sh
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$TRAVIS_BUILD_DIR/z3-4.8.4.d6df51951f4c-x64-ubuntu-14.04/bin

rvm:
  - 2.5.1
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
