#!/usr/bin/env ruby
# frozen_string_literal: true

# Advent of Code 2018
#
# Robert Haines
#
# Public Domain

lib = ::File.expand_path('lib', __dir__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

require 'aoc2018/extra/cli'

day = AOC2018::Extra::CLI.parse_params(ARGV)

unless day
  warn 'Usage: aoc-2018 <day>'
  exit 1
end

AOC2018::Extra::CLI.run_day(day)
